### ISSUE TITLE
Modernization of Drugs/Prescriptions/Inventory

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#692]
## GOAL

There are many areas of our codebase that reference drugs, prescriptions, sales, inventory, pharmacies, etc. All of the logic around these entities should be centralized in services. Currently, the logic is mostly coupled with the view (e.g.: direct database calls from the view, sometimes even copy/pasted several times).

As with all of the work in the backend modernization project, the view and the business logic/database logic should be separated so that (if we wanted to) we could make an OpenEMR REST API. Where possible, Doctrine should be used to provide a more modern object oriented approach, however, we know that `patient_data` and similar dynamic tables are a non-starter with Doctrine.

## TASKS

- [x] @MatthewVita, @kofiav, @juggernautsei: Find out all of the tables that deal with drugs, prescriptions, sales, inventory, pharmacies.
- [ ] @MatthewVita, @kofiav: Study how the code works currently with reference to the following tables:
  - `drugs`
  - `drug_inventory`
  - `drug_sales`
  - `drug_templates`
  - `product_warehouse`
  - `prices`
  - `prescriptions`
  - `pharmacies`
  - `phone_numbers`
  - `addresses`
  - `erx_drug_paid`
  - `erx_narcotics`
  - `erx_rx_log`
  - `patient_data`
- [ ] @juggernautsei: Think about how these should be split up into here: https://github.com/openemr/openemr/tree/master/services (remember that very specific services are fine too. For example, we already have a `PatientService` (recently created and doesn't do too much, however). It would be totally fine to create a `PatientPrescriptionService` that is called into from something like `patientServiceInstance->getAllPrescriptionsForPatient(pid)`). In other words, the `PatientService` could be a _facade_ to all of these other services.
- [ ] @MatthewVita: Start to think about how we can separate up the work in terms of making individual tickets (obviously this current ticket doesn't encapulate everything)

## HANGOUTS

Once Sherwin makes some progress with the "Think about how these should be split up" task, I believe it is a great idea to have a Google Hangout so he can explain his findings. We have to have a strong coding foundation for all of these different entities.

### NOTE FROM MATTHEW

Most of my free time has been focusing on shipping the Version 1 BETA of https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide - I am definitely going to make time for this project, but I want you all to know that the cloud guide is my #1 priority at the moment. Thank you for understanding.

**Comment by MatthewVita** [comment]
@kofiav in the modernization space, I've been primarily working on https://github.com/openemr/openemr/issues/606 (we're a little over halfway done with release 1 alpha!). I'd be up for working on _this_ ticket with you, if you're up for it.

It's going to be a tad rough :)

**Comment by kofiav** [comment]
Sure I can work with you on this. Thanks for the chart tracker review and merging the PR. What makes prescriptions service rough? Dynamic tables again?

**Comment by robertdown** [comment]
Definitely separate it, could come in really handy as @juggernautsei and I work on the MAR

**Comment by MatthewVita** [comment]
Hi @kofiav,

Sorry for my delay. I was sick last week and didn't have much time for anything after work :).

The part that makes this rough is how much code there is around it. We will be touching a good chunk of the software!

I suppose a good first step is for us to study the following tables and how the code references them:

- drugs
- drug_inventory
- drug_sales
- drug_templates
- product_warehouse
- prices
- prescriptions
- ...and, of course, patient_data is linked here too

Once we get a good idea of how everything works, we'll take @robertdown's advice and split up the ticket by drugs and prescriptions.

-m

**Comment by kofiav** [comment]
Awesome, I'll take a look at the tables some time this week then we can decide how to divide the tasks.

**Comment by juggernautsei** [comment]
You can assign me some of the work as well. I have a good working knowledge of this section.

**Comment by MatthewVita** [comment]
Hi @juggernautsei,

Hope you are well.

I'm not exactly sure how to slice up the work just yet. Can you help by listing all of the tables relating to drugs and prescriptions in OpenEMR? Here's what I have thus far:

- drugs
- drug_inventory
- drug_sales
- drug_templates
- product_warehouse
- prices
- prescriptions
- ...and, of course, patient_data is linked here too

Thanks!

**Comment by juggernautsei** [comment]
@MatthewVita  Glad your feeling better. The list seems to be complete. But thinking about prescriptions only those include: 

- pharmacies 
- phone_numbers 
- addresses 

This is all related information. When the weno code get's accepted then there will be:

- erx_drug_paid
-  erx_narcotics
-  erx_rx_log

Could you provide an overview of what we are going to accomplish in this modernization endeavor?

**Comment by MatthewVita** [comment]
@kofiav and @juggernautsei: turns out my virus came back full force! I am on 3 prescriptions now and am slowly recovering. Sorry for my delay, as a result.

Please see the very top description of this issue. I made sure our goal was clearly defined as per Sherwin's point and gave everyone tasks to work on. Let's do this!

**Comment by kofiav** [comment]
Glad to see that this is taking shape and responsibilities are being divided. Sorry to hear about your virus, hope you get better soon!

**Comment by MatthewVita** [comment]
Hi @juggernautsei, 

Okay, I am back to looking at this ticket. I have two questions for you:

- I understand how the `drug_inventory` is used via `/interface/drugs/drug_inventory.php`, but where does `product_warehouse` fall into the mix? I'm failing to understand what it is used for.
- Do you know if users often customize drug templates?

Thanks,
Matthew

**Comment by juggernautsei** [comment]
product warehouse you can find in the globals under Features > Drug and Products in the drop down you will see non-drug products. The office that sells items other than drugs can list them in that table. 

The drug template is not customized all that often to my knowledge. It is used as is and has sufficed since 2012. I see small changes being added to the prescription template like the RxNorms but I don't know who is making these changes. @bradymiller should know.

**Comment by MatthewVita** [comment]
Hi @juggernautsei,

Looks like Features > Drug and Products boils down to the global `inhouse_pharmacy`. I'm having a hard time seeing where that intersects with the `product_warehouse` table.

Thanks,
Matthew

**Comment by juggernautsei** [comment]
Have you looked at line 254 of the add_edit_drug.php?

**Comment by MatthewVita** [comment]
I do see that, but I'm confused on where this fits in with global `inhouse_pharmacy`?

**Comment by juggernautsei** [comment]
http://www.open-emr.org/wiki/index.php/Pharmacy_Dispensary_Module

When these instructions are followed the table product_warehouse is filled in from the add form in the middle of the page.

**Comment by MatthewVita** [comment]
Hi Sherwin,

Thank you so much for that.

I see now that warehouse is referenced in function `genWarehouseList` in add_edit_lot.php. However, it looks like it's pulling from `list_options` table and not the `product_warehouse` table.

For example:
```
use openemr;

SELECT * FROM list_options WHERE list_id = 'warehouse' AND activity = 1 ORDER BY seq, title
```

As far as I can tell, `product_warehouse` is not really used...

**Comment by MatthewVita** [comment]
Would be good for @kofiav to study and chime in on this as we need to really understand this code before we "doctrinize" it :)

**Comment by kofiav** [comment]
@MatthewVita @juggernautsei 

My bad, I've been dealing with some health complications myself recently, that's why I've been quiet. Thank you both for progressing this further and sharing your thoughts.

I will study the code and chime in in the next couple of days, I promise :)

**Comment by MatthewVita** [comment]
Feel better!

**Comment by juggernautsei** [comment]
@MatthewVita @kofiav 
I believe you are right that the product_warehouse is not used in any useful way.
When I filled out the inventory form the product_warehouse table was populated. However, there seems to be no use for the table except to hold the information from the form and it can be modified from the prescription form.

**Comment by MatthewVita** [comment]
Okay. Thanks Sherwin. You're awesome.

Just so I'm 100% clear. A warehouse would be the drug company's facility that a practice/hospital buys medicines from. An inventory (system) is the purchased drugs on hand at a practice/hospital.

Is this correct?
