### ISSUE TITLE
bug: find and fix easy php warnings, deprecated or errors

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#7598]
### Describe the bug

review these php issues in the [main demo php error log](https://demo.openemr.io/log/logPhp.txt) and then [open a PR](https://github.com/openemr/openemr/pulls) with a fix :)

**Comment by SSJGoku47** [comment]
Hello i want to work on this

**Comment by migumnakkittikul** [comment]
Hi, is it possible if I can work on this too?

**Comment by bradymiller** [comment]
hi @migumnakkittikul , definitely ok. go for it

**Comment by kojiromike** [comment]
This may help. It's a shell script that fetches the log, removes the debug throttling lines, removes the timestamps, and deduplicates the remaining entries without changing their order. (Sorting would make the tracebacks much harder to read.)

It isn't perfect, but I think it's a good blend of simple and functional.

```sh
curl https://demo.openemr.io/log/logPhp.txt |
    grep -vF 'DEBUG: throttling' |
    sed -e 's/^\[[^]]*] //' -e 's/^\[[^]]*]//' |
    awk '!s[$0]++'
```

**Comment by kojiromike** [comment]
Looking at this log, I am beginning to wonder how many of these warnings and errors are due to someone (or somebot) directly requesting a url to a php file that is intended to be included in another page instead of run directly.

**Comment by kojiromike** [comment]
## Issues from reducedLog.txt analysis

Found and reported the following PHP warnings/errors from log analysis:

- [ ] #9470 - Undefined $tokens array in RxList::parseToTokens() (HIGH priority - hundreds of warnings)
- [ ] #9471 - Undefined variables in find_code_dynamic_ajax.php when $what == 'codes'
- [ ] #9472 - Undefined array keys in CAMOS form
- [x] #9459 - Multiple undefined array key/variable warnings in transfer_summary form (already reported)

Also added comment to #9451 documenting 4 additional files needing direct access guards.

**Comment by kojiromike** [comment]
Alrighty, I believe I've accounted for all the issues that I saw in the logs yesterday that I can't rule out were already fixed in 7.0.4. I created issues for all of them, and made them sub-issues of this ticket for tracking. There may be new issues in future logs, especially because #9451 can't be solved until openemr has a front controller, but we can definitely tackle a bunch of these.

**Comment by kojiromike** [comment]
@stephenwaite what do you think about closing this ticket once all the subtasks are done, and creating a new one when we have updated all the demo stuff and are tracking new logs for the future release?
